#!/bin/sh

TESTFILES="${srcdir}/testdata/invalid ${srcdir}/testdata/invalid-unicode"

run_test() {
    local prog=$1
    local prefix=$2

    run_testprog $prog $prefix
    if ! cmp $prefix.out $prefix.$prog.stderr >/dev/null; then
        echo >&2
        echo "### $prefix ($prog) failed:" >&2
        cat $prefix.in >&2
        echo "### expected output:" >&2
        cat $prefix.out >&2
        echo "### actual output:" >&2
        cat $prefix.$prog.stderr >&2
        exit 1
    fi
}

. ${srcdir}/run-test
