#!/bin/sh

TESTFILES="${srcdir}/testdata/valid"

run_test() {
    local prog=$1
    local prefix=$2

    run_testprog $prog $prefix

    if ! ${srcdir}/json-compare.py $prefix.in $prefix.$prog.stdout \
        >$prefix.$prog.cmp-stdout
    then
        echo >&2
        echo "### $prefix ($prog) failed:" >&2
        cat $prefix.in >&2
        if [ -f $prefix.$prog.stdout ]; then
            echo "### output:" >&2
            cat $prefix.$prog.stdout >&2
        fi
        if [ -s $prefix.$prog.stdout ]; then
            echo "### compare output:" >&2
            cat $prefix.$prog.cmp-stdout >&2
        fi
        exit 1
    fi
}

. ${srcdir}/run-test
