os: linux
language: c
compiler:
  - gcc
  - clang
env:
  - BUILD_TYPE=cmake
  - BUILD_TYPE=autotools
  - BUILD_TYPE=coverage
  - BUILD_TYPE=fuzz
matrix:
  include:
    # gcc + valgrind (cmake)
    - compiler: gcc
      env: BUILD_TYPE=cmake
      addons:
        apt:
          packages:
            - cmake
            - valgrind
      script:
        - mkdir build
        - build
        - cmake -DJANSSON_TEST_WITH_VALGRIND=ON ..
        - cmake --build .
        - ctest --output-on-failure

    # clang + valgrind (cmake)
    - compiler: clang
      env: BUILD_TYPE=cmake
      addons:
        apt:
          packages:
            - cmake
            - valgrind
      script:
        - mkdir build
        - build
        - cmake -DJANSSON_TEST_WITH_VALGRIND=ON ..
        - cmake --build .
        - ctest --output-on-failure

    # gcc (autotools)
    - compiler: gcc
      env: BUILD_TYPE=autotools
      script:
        - autoreconf -f -i
        - CFLAGS=-Werror ./configure
        - make check

    # clang (autotools)
    - compiler: clang
      env: BUILD_TYPE=autotools
      script:
        - autoreconf -f -i
        - CFLAGS=-Werror ./configure
        - make check

    # coverage (cmake)
    - compiler: gcc
      env: BUILD_TYPE=coverage
      addons:
        apt:
          package:
            - cmake
            - lcov
            - curl
      script:
        - mkdir build
        - build
        - cmake -DJANSSON_COVERAGE=ON -DJANSSON_COVERALLS=ON -DCMAKE_BUILD_TYPE=Debug ..
        - cmake --build .
        - cmake --build . --target coveralls

    # fuzz
    - compiler: gcc
      env: BUILD_TYPE=fuzz
      script:
        - ./test/ossfuzz/travisoss.sh

    # lint (requires clang 9.0 for new enough clang-format)
    - compiler: gcc
      env: BUILD_TYPE=lint
      dist: bionic
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-bionic-9.0
          packages:
            - clang-9.0
      script:
        - ./scripts/clang-format-ci

  allow_failures:
    - compiler: gcc
      env: BUILD_TYPE=coverage
